#pragma once

enum class [[nodiscard]] Tile
{
    Reserved,
    FloorUp60Small,
    FloorUp60Big,
    FloorDown60Big,
    FloorDown60Small,
    FloorUp120Small,
    FloorDown120Small,
    CeilDown60Small,
    CeilDown60Big,
    CeilUp60Big,
    CeilUp60Small,
    FloorUp120Big,
    FloorDown120Big,
    Empty,
    Finish,
    FloorUp45,
    FloorDown45,
    CeilDown120Big,
    CeilUp120Big,
    MagPlus,
    SpikeUp,
    CeilDown45,
    CeilUp45,
    CeilDown120Small,
    CeilUp120Small,
    SpikeLeft,
    Block,
    SpikeRight,
    Empty2,
    Empty3,
    Empty4,
    MagNeg,
    SpikeDown,
};
